import { Project, Skill, Experience } from '@/types';

export const projects: Project[] = [
  {
    id: 'p1',
    title: 'Lumina Dashboard',
    description: 'A real-time analytics dashboard with beautiful data visualisations and team collaboration features.',
    longDescription: 'Built with React and D3.js, Lumina provides real-time insights with a stunning dark-mode UI. Features include live charts, customisable widgets, role-based access, and WebSocket-powered updates.',
    tags: ['React', 'TypeScript', 'D3.js', 'WebSocket', 'Node.js'],
    category: 'web',
    image: 'lumina',
    liveUrl: 'https://example.com',
    githubUrl: 'https://github.com',
    featured: true,
    year: 2024,
  },
  {
    id: 'p2',
    title: 'Flowstate — Task Manager',
    description: 'A minimalist productivity app with drag-and-drop boards, calendar sync, and focus mode.',
    longDescription: 'Flowstate is designed around the philosophy that the best tool gets out of your way. Smooth DnD interactions, a clean visual hierarchy, and intelligent reminders make staying focused effortless.',
    tags: ['React Native', 'Expo', 'SQLite', 'Reanimated'],
    category: 'mobile',
    image: 'flowstate',
    liveUrl: 'https://example.com',
    githubUrl: 'https://github.com',
    featured: true,
    year: 2024,
  },
  {
    id: 'p3',
    title: 'Aurora Design System',
    description: 'An open-source component library with 60+ accessible components, theming, and full Storybook docs.',
    longDescription: 'Aurora provides a cohesive design language across web products. Built with accessibility at the core (WCAG AA), it includes design tokens, CSS variables, and React components that are fully tested.',
    tags: ['React', 'TypeScript', 'Storybook', 'CSS Modules', 'Vitest'],
    category: 'oss',
    image: 'aurora',
    githubUrl: 'https://github.com',
    featured: true,
    year: 2023,
  },
  {
    id: 'p4',
    title: 'Shopify Theme — Horizon',
    description: 'A performance-first Shopify 2.0 theme with a 99 Lighthouse score and dynamic product sections.',
    longDescription: 'Horizon redefines Shopify storefronts with zero-CLS transitions, lazy-loaded media, and a modular section architecture that empowers merchants to customise without code.',
    tags: ['Liquid', 'JavaScript', 'CSS', 'Shopify CLI'],
    category: 'web',
    image: 'horizon',
    liveUrl: 'https://example.com',
    featured: false,
    year: 2023,
  },
  {
    id: 'p5',
    title: 'Sonic — Music Player UI',
    description: 'A concept music player with fluid animations, waveform visualisations, and gesture controls.',
    longDescription: 'Sonic explores what a modern music interface could feel like — springy gesture-based navigation, real-time audio waveform rendering via the Web Audio API, and delightful micro-animations throughout.',
    tags: ['React', 'Framer Motion', 'Web Audio API', 'Canvas'],
    category: 'design',
    image: 'sonic',
    githubUrl: 'https://github.com',
    featured: false,
    year: 2023,
  },
  {
    id: 'p6',
    title: 'DevPulse — GitHub Tracker',
    description: 'Track your open-source contributions, visualise commit history, and set coding goals.',
    longDescription: 'DevPulse wraps the GitHub GraphQL API in a clean developer-focused dashboard. See your contribution heatmap, top languages, PR review stats, and set personal goals with streak tracking.',
    tags: ['Next.js', 'GraphQL', 'GitHub API', 'Recharts'],
    category: 'web',
    image: 'devpulse',
    liveUrl: 'https://example.com',
    githubUrl: 'https://github.com',
    featured: false,
    year: 2022,
  },
];

export const skills: Skill[] = [
  { name: 'React', level: 95, category: 'frontend' },
  { name: 'TypeScript', level: 92, category: 'frontend' },
  { name: 'CSS / Animations', level: 90, category: 'frontend' },
  { name: 'Next.js', level: 85, category: 'frontend' },
  { name: 'React Native', level: 80, category: 'frontend' },
  { name: 'Node.js', level: 85, category: 'backend' },
  { name: 'GraphQL', level: 78, category: 'backend' },
  { name: 'PostgreSQL', level: 72, category: 'backend' },
  { name: 'Redis', level: 68, category: 'backend' },
  { name: 'Docker', level: 75, category: 'tools' },
  { name: 'Git / CI-CD', level: 88, category: 'tools' },
  { name: 'Figma', level: 82, category: 'design' },
  { name: 'Motion Design', level: 76, category: 'design' },
];

export const experiences: Experience[] = [
  {
    id: 'e1',
    company: 'Vercel',
    role: 'Senior Frontend Engineer',
    period: '2022 — Present',
    description: [
      'Led the redesign of the analytics dashboard, increasing user engagement by 40%.',
      'Architected a component library used across 6 internal products, cutting UI dev time by 30%.',
      'Mentored 3 junior engineers and drove the adoption of TypeScript strict mode across the team.',
    ],
    tech: ['React', 'TypeScript', 'Next.js', 'Turborepo'],
  },
  {
    id: 'e2',
    company: 'Shopify',
    role: 'Frontend Developer',
    period: '2020 — 2022',
    description: [
      'Built and shipped the new Checkout UI Extensions framework used by 10,000+ merchants.',
      'Improved Lighthouse performance scores from 68 to 97 across checkout flows.',
      'Collaborated with design teams to create and document the Polaris design system updates.',
    ],
    tech: ['React', 'Liquid', 'GraphQL', 'Storybook'],
  },
  {
    id: 'e3',
    company: 'Freelance',
    role: 'Full-Stack Developer & Designer',
    period: '2018 — 2020',
    description: [
      'Delivered 20+ projects for startups and agencies across e-commerce, SaaS, and media.',
      'Specialised in high-performance landing pages and interactive marketing sites.',
      'Provided UX audits and design system consulting for early-stage companies.',
    ],
    tech: ['React', 'Node.js', 'WordPress', 'Figma'],
  },
];
